name: tene_medical
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  pin_code_fields: ^7.4.0
  smooth_page_indicator: ^1.0.0+2
  flutter: 
    sdk: flutter
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: any
  lints: any
  sizer: ^2.0.15
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

